export enum PIPEDRIVE_DEAL_STATUS {
  WON = 'won',
  LOST = 'lost'
}

export const PIPEDRIVE_DEAL_STATUS_OPTIONS = [PIPEDRIVE_DEAL_STATUS.WON, PIPEDRIVE_DEAL_STATUS.LOST]

export type PIPEDRIVE_DEAL_STATUS_TYPE = PIPEDRIVE_DEAL_STATUS.WON | PIPEDRIVE_DEAL_STATUS.LOST;

export function IsAPipedriveDealStatusOption(status: PIPEDRIVE_DEAL_STATUS): boolean {
  return PIPEDRIVE_DEAL_STATUS_OPTIONS.includes(status);
}
